name: Build Vector DB

on: 
    push:
      branches: ["main"]
    pull_request_target:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v5
        - name: Set up Python 3.8
          uses: actions/setup-python@v6
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            sudo apt-get install nuget
            nuget config -Set repositoryPath=${{ github.workspace }}/packages -configfile ${{ github.workspace }}/nuget.config
            nuget.exe setapikey ${{ secrets.NUGET_API_KEY }} -source "https://pkgs.dev.azure.com/intelliTect/_packaging/EssentialCSharp/nuget/v3/index.json"
            nuget.exe restore ${{ github.workspace }}/EssentialCSharp.Chat/packages.config -PackagesDirectory ${{ github.workspace }}/packages
            python -m pip install --upgrade pip
            pip install -r ${{ github.workspace }}/EssentialCSharp.Chat/requirements.txt
            ls ${{ github.workspace }}/packages