name: Build Vector DB

on: 
    push:
      branches: ["main"]
    pull_request_target:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.11.4
          uses: actions/setup-python@v2
          with:
            python-version: 3.11.4
        - name: Install dependencies
          shell: bash
          run: |
            sudo apt install libpq5
            sudo apt-get install nuget
            nuget config -Set repositoryPath=${{ github.workspace }}/packages -configfile ${{ github.workspace }}/nuget.config
            nuget sources Update -Name EssentialCSharp -username unused -password ${{ secrets.AZURE_DEVOPS_PAT }} -src "https://pkgs.dev.azure.com/intelliTect/_packaging/EssentialCSharp/nuget/v3/index.json"
            nuget restore ${{ github.workspace }}/EssentialCSharp.Chat/packages.config -PackagesDirectory ${{ github.workspace }}/packages
            python -m pip install --upgrade pip
            pip install -r ${{ github.workspace }}/EssentialCSharp.Chat/requirements.txt
        - name: Build dotenv
          shell: bash
          run: |
            echo "VECTOR_DB_CONNECTION_STRING=${{ secrets.POSTGRES_CONNECTION_STRING }}\n" > ${{ github.workspace }}/.env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}\n" >> ${{ github.workspace }}/.env
            echo "OPENAI_ORG_ID=${{ secrets.OPENAI_ORG_ID }}\n" >> ${{ github.workspace }}/.env
        - name: Build Vector DB
          shell: bash
          run: |
            ls -la ${{ github.workspace }}
            python ${{ github.workspace }}/EssentialCSharp.Chat/build_vector_db.py "${{ github.workspace }}/packages/ContentFeedNuget.1.1.0-3639/Markdown/"